### PR TITLE
Made output more uniform

### PR DESCRIPTION
**Pull request by Racool198**
Hope it helps!

### CODE REVIEW

**Comment by xxcodianxx** [comment]
need help reviewing this one

**Comment by xxori** [comment]
LGTM

**Review by xxori — APPROVED** [review]
i like it

**Comment by xxori** [comment]
| Merge Rejected |
|--------|
| I dont like it |

**Comment by xcodian** [comment]
need more work on this

**Comment by xxori** [comment]
<details><summary>Details</summary>
<p>

[ඞ](https://www.reddit.com/r/unicodecirclejerk/comments/izk1ef/%E0%B6%9E_unicode_among_us_crewmate_symbol/)

</p>
</details>

**Pull request closed without merging**
